#!/bin/bash
echo "=== Todo App Status ==="
echo "UI:      http://localhost:5174 (Vite + React with live reload)"
echo "API:     http://localhost:3001 (Hono + YAML backend)"
echo "Data:    ./todo/todos.yaml (UI polls every 3s for manual changes)"
echo ""
echo "Commands:"
echo "  task todo:dev      # Start full stack (Vite + API)"
echo "  task todo:stop     # Stop all servers"
echo "  task todo:restart  # Restart reliably"
echo "  task todo:status   # This status"
echo ""
echo "The app is fully implemented per the plan."
echo "Run 'task todo:dev' to start it now."
echo ""
ps aux | grep -E "(vite|tsx|node-server|todo-app)" | grep -v grep || echo "No todo-app processes currently running."
